name: nut x86 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Locate include files
      run: sudo make locate EXISTS-NUT-INCLUDE=no
    - name: Build nut
      run: sudo make
